<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\IBEBarcode.Templates\IBEBarcode.Templates.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="PDFsharp" Version="6.2.4" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>IBEBarcode.Printing</RootNamespace>
  </PropertyGroup>

</Project>
