<Project Sdk="Microsoft.NET.Sdk.BlazorWebAssembly">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <OverrideHtmlAssetPlaceholders>true</OverrideHtmlAssetPlaceholders>
    <WasmBuildNative>true</WasmBuildNative>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly" Version="10.0.12" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.DevServer" Version="10.0.12" PrivateAssets="all" />
    <PackageReference Include="SkiaSharp.NativeAssets.WebAssembly" Version="4.152.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\IBEBarcode.Core\IBEBarcode.Core.csproj" />
    <ProjectReference Include="..\IBEBarcode.Rendering\IBEBarcode.Rendering.csproj" />
    <ProjectReference Include="..\IBEBarcode.Templates\IBEBarcode.Templates.csproj" />
    <ProjectReference Include="..\IBEBarcode.Printing\IBEBarcode.Printing.csproj" />
  </ItemGroup>

</Project>
